### ISSUE TITLE
Instructions for running with docker-compose

### ISSUE THREAD

**Issue by joepio** [pdsinterop/php-solid-server#40]
First off: awesome work! This really helps make the Solid ecosystem more mature :).

Since there's a `docker-compose.yml` file, I'd love to use that to run this project locally. However, I'm not getting it to work, and I'm not sure what I'm doing wrong.

When I run `docker-compose up`, the image is properly pulled and it's `Attaching to solid-php-server`, but from then on I can't get a connection. The compose file seems to correctly expose port 80, but I can't make a connection. Also, the logs are empty: `docker logs solid_php`. 

Thanks in advance!

**Comment by michielbdejong** [comment]
I never tried the docker-compose but I think it should work with
https://github.com/pdsinterop/php-solid-server/blob/master/run-solid-test-suite.sh#L9
https://github.com/pdsinterop/php-solid-server/blob/master/run-solid-test-suite.sh#L23

I'll see if I can set up a public instance

**Comment by michielbdejong** [comment]
I just tried:
```sh
docker build -t server .
docker run -d --network=host server
```
and now see 'Hello, World!' on https://pss.pdsinterop.net/

**Comment by michielbdejong** [comment]
When browsing to https://pss.pdsinterop.net/login I see '405 Method Not Allowed'.
I tried `fetch('', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: 'username=alice&password=alice123' });` from that page but got a 405 for that as well.

**Comment by michielbdejong** [comment]
Ah, https://pss.pdsinterop.net/profile/card#me shows something meaningful :)

**Comment by michielbdejong** [comment]
Here is the entire history from a clean Ubuntu server, including LetsEncrypt setup:
```sh
apt install certbot
certbot certonly --standalone

git clone https://github.com/pdsinterop/php-solid-server
cd php-solid-server
mkdir tls
cp /etc/letsencrypt/live/pss.pdsinterop.net/privkey.pem tls/server.key
cp /etc/letsencrypt/live/pss.pdsinterop.net/fullchain.pem tls/server.cert

snap install docker
docker build -t server .
docker run -d --network=host -e SERVER_ROOT=https://pss.pdsinterop.net -e USERNAME=alice -e PASSWORD=alice123 -v `pwd`/tls:/tls server
```

**Comment by michielbdejong** [comment]
And see https://pss.pdsinterop.net/storage/

**Comment by ylebre** [comment]
Adding on to the pile of information - I have an instance running locally with docker-compose, but the setup is different.
It consist of these files:
docker-compose.yml
apache.conf
php-solid-server/
php-solid-pubsub-server/

docker-compose.yml:
```
version: '3'
services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - ./php-solid-server/:/var/www/
            - ./php-solid-pubsub-server/:/var/websocket/
            - ./apache.conf:/etc/apache2/sites-enabled/001-default-ssl.conf
```
apache.conf:
```
<VirtualHost *:443>
    SSLEngine On
	SSLCertificateFile /tls/server.cert
	SSLCertificateKeyFile /tls/server.key
    ServerName localhost
    DocumentRoot /var/www/html/
</VirtualHost>
```

and directories php-solid-server and php-solid-pubsub-server checked out from github.

The caveat is that the pubsub server has to be started up manually (php /var/websocket/server/server.php) from the commandline.
